apiVersion: v1
kind: Service
metadata:
  name: simple-go-api
  namespace: backend
  labels:
    run: simple-go-api
spec:
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32715
  selector:
    run: simple-go-api
  type: LoadBalancer